disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "simonedimaria's blog"

[params]
    displayName = "EN"
    isoCode = "en"
    rtl = false
    logo = "static/logo.png"
    secondaryLogo = "static/logo.png"
    description = "simonedimaria's blog"
    dateFormat = "2 January 2006"

[params.author]
    name = "simonedimaria"
    image = "/img/gatto-stregone-ciccione.jpeg"
    headline = "`Web2/Web3 CTF player for TheRomanXpl0it & mhackeroni`"
    bio = "*I make a bunch of electrons dance on some rock to hack stuff*"
    links = [
        { x-twitter = "https://x.com/dimariasimone" },
        { github = "https://github.com/simonedimaria" }
    ]
