# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = false
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
defaultBackgroundImage = ""
defaultFeaturedImage = ""
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
    layout = "fixed-fill-blur"

[footer]
    showMenu = true
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = true
    showScrollToTop = true

[homepage]
    layout = "hero" # valid options: page, profile, hero, card, background, custom
    homepageImage = "img/banner.png" # used in: hero, and card
    mainSections = ["posts", "projects"]
    showRecent = true
    showRecentItems = 5
    showMoreLink = true
    showMoreLinkDest = "/posts/"
    cardView = true
    cardViewScreenWidth = false
    layoutBackgroundBlur = false # only used when layout equals background

[article]
    showDate = true
    showViews = false
    showLikes = false
    showDateOnlyInArticle = true
    showDateUpdated = true
    showAuthor = true
    showHero = true
    heroStyle = "big" # valid options: basic, big, background
    layoutBackgroundBlur = true
    layoutBackgroundHeaderSpace = true
    showBreadcrumbs = true
    showDraftLabel = true
    showEdit = false
    editAppendPath = true
    seriesOpened = false
    showHeadingAnchors = true
    showPagination = true
    invertPagination = false
    showReadingTime = true
    showTableOfContents = true
    showTaxonomies = true
    showAuthorsBadges = false
    showWordCount = true
    showZenMode = true

[list]
    showHero = false
    # heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
    layoutBackgroundBlur = true
    layoutBackgroundHeaderSpace = true
    showBreadcrumbs = true
    showSummary = true
    showViews = false
    showLikes = false
    showTableOfContents = true
    showCards = false
    orderByWeight = false
    groupByYear = true
    cardView = false
    cardViewScreenWidth = false
    constrainItemsWidth = false

[sitemap]
    excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
    showTermCount = true
    showHero = false
    showBreadcrumbs = true
    showViews = false
    showLikes = false
    showTableOfContents = true
    cardView = false

[term]
    showHero = false
    heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
    showBreadcrumbs = true
    showViews = false
    showLikes = false
    showTableOfContents = true
    groupByYear = false
    cardView = false
    cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]

[verification]

[rssnext]
